const SAMPLE_RATE = 48000;
const TIMELINE_LENGTH_IN_SECONDS = 15 * 60; // 15 minutes
const MIX_MAX_TRACKS = 16;
const PACKET_SIZE = 960;
const MIPMAP_HALF_SIZE = 2**22;
const MINIMUM_WAVEFORM_WINDOW_LEN = 900;
const LEFT_CONTROLS_WIDTH = 250;

const resolutions = [MIPMAP_HALF_SIZE];
let curr = MIPMAP_HALF_SIZE;
while(curr > MINIMUM_WAVEFORM_WINDOW_LEN){
    curr = curr / 2;
    resolutions.push(curr);
}

const MIPMAP_RESOLUTIONS = resolutions;
const MIN_SAMPLES_PER_PX = 10;
const EVENT_QUEUE_LENGTH = 100000;

export const CONSTANTS = {
    SAMPLE_RATE,
    TIMELINE_LENGTH_IN_SECONDS,
    MIX_MAX_TRACKS,
    PACKET_SIZE,
    MIPMAP_HALF_SIZE,
    MINIMUM_WAVEFORM_WINDOW_LEN,
    MIPMAP_RESOLUTIONS,
    MIN_SAMPLES_PER_PX,
    EVENT_QUEUE_LENGTH,
    LEFT_CONTROLS_WIDTH,
};
