export const DOMCommands = {
    DRAW_CANVAS_CONTAINER: "DRAW_CANVAS_CONTAINER",
    DRAW_MEASURE_TICK_CONTAINER: "DRAW_MEASURE_TICK_CONTAINER",
    DRAW_TRACK_ONE_WAVEFORMS: "DRAW_TRACK_ONE_WAVEFORMS",
    DRAW_TRACK_TWO_WAVEFORMS: "DRAW_TRACK_TWO_WAVEFORMS",
    FILL_SELECTED_REGION_MEASURE_TICKS: "FILL_SELECTED_REGION_MEASURE_TICKS",
    FILL_SELECTED_REGION_TRACK_ONE: "FILL_SELECTED_REGION_TRACK_ONE",
    FILL_SELECTED_REGION_TRACK_TWO: "FILL_SELECTED_REGION_TRACK_TWO",
    DRAW_PLAYHEAD: "DRAW_PLAYHEAD",

} as const;

export const DOMElements = {
    CANVAS_CONTAINER: "CANVAS_CONTAINER",
    MEASURE_TICK_CONTAINER: "MEASURE_TICK_CONTAINER",
    TRACK_ONE: "TRACK_ONE",
    TRACK_TWO: "TRACK_TWO",
    TOUCH_OVERLAY: "TOUCH_OVERLAY",
} as const;