

export const MIXER_PARAMS = {
    MIX_MASTER_VOLUME: "MIX_MASTER_VOLUME",
    STAGING_MASTER_VOLUME: "STAGING_MASTER_VOLUME",
    METRONOME_GAIN: "METRONOME_GAIN",
    TRACK_0_VOLUME: "TRACK_0_VOLUME",
    TRACK_1_VOLUME: "TRACK_1_VOLUME",
    TRACK_2_VOLUME: "TRACK_2_VOLUME",
    TRACK_3_VOLUME: "TRACK_3_VOLUME",
    TRACK_4_VOLUME: "TRACK_4_VOLUME",
    TRACK_5_VOLUME: "TRACK_5_VOLUME",
    TRACK_6_VOLUME: "TRACK_6_VOLUME",
    TRACK_7_VOLUME: "TRACK_7_VOLUME",
    TRACK_8_VOLUME: "TRACK_8_VOLUME",
    TRACK_9_VOLUME: "TRACK_9_VOLUME",
    TRACK_10_VOLUME: "TRACK_10_VOLUME",
    TRACK_11_VOLUME: "TRACK_11_VOLUME",
    TRACK_12_VOLUME: "TRACK_12_VOLUME",
    TRACK_13_VOLUME: "TRACK_13_VOLUME",
    TRACK_14_VOLUME: "TRACK_14_VOLUME",
    TRACK_15_VOLUME: "TRACK_15_VOLUME",
}